name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python Logic Tasks
      id: python-logic-tasks
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 5
        max-score: 10
        setup-command: pip install -r requirements.txt
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-LOGIC-TASKS_RESULTS: "${{steps.python-logic-tasks.outputs.result}}"
      with:
        runners: python-logic-tasks
